id: P006717
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:18:57.676818
source_metadata:
  id: bdr:W23731
  title: རྒྱལ་མཚན་རྩེ་མོའི་དཔུང་རྒྱན་སོགས
  author: ''
  volumes:
    28dfd2c402434a0db11b180a68c76908:
      image_group_id: I2550
      title: ''
      volume_number: 1
      total_pages: 18
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
