id: P006717
initial_creation_type: ocr
source_metadata:
  id: bdr:W23731
  title: རྒྱལ་མཚན་རྩེ་མོའི་དཔུང་རྒྱན་སོགས
  author: ''
  volumes:
    28dfd2c402434a0db11b180a68c76908:
      image_group_id: I2550
      title: ''
      volume_number: 1
      total_pages: 18
